<html>

<head>
    <title>Clinic Swing Login Panel</title>
    <link rel="stylesheet" type="text/css" href="1style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
</head>

<body>


    <title>Clinic Swing Login Panel</title>
    <link rel="stylesheet" type="text/css" href="1style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">


    <div class="loginbox">
        <img src="http://nktrust.ca/img_avatar5.png" class="avatar">
        <h1>Sing-Up Here</h1>
        <form method="POST" action="">
            <p>Username</p>
            <input type="text" name="name" placeholder="Enter Username" required="">
            <p>Em@il</p>
            <input type="text" name="name" placeholder="Enter email" required="">
            <p>Password</p>
            <input type="password" name="password" placeholder="Enter Password" required="">
            <p>Conform Password</p>
            <input type="password" name="password" placeholder="Enter Password" required="">
            <input type="submit" name="submit" value="Sing-Up">
            <div class="Sing-Up">
                <h3>Already Have An Account?</h3>
                <h1><a href="LOGIN.html"> Log in Now</a></h1>
            </div>

        </form>
    </div>

</body>

</html>